[global]
modules = ["cwd", "git", "prompt"]

[modules]

    [modules.cwd]

        [modules.cwd.style]
        foreground = 15
        background = "blue"
        text_properties = "italic"

    [modules.git]

        [modules.git.style]
        foreground = 15
        background = "cyan"

    [modules.prompt]

        [modules.prompt.style_success]
        foreground = 15
        background = "green"
        text_properties = "bold"

        [modules.prompt.style_error]
        foreground = 15
        background = "red"
        text_properties = "bold"
